name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
      greeting:
        description: 'Greeting message'
        required: false
        default: 'Hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}!"
